In [1]:
import numpy as np

In [4]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros((2, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
np.ones((5, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [101]:
np.random.seed(10)
np.random.random((3, 5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096]])

In [107]:
np.random.seed(15)
np.random.randint(10, 20, size=(2,4))

array([[18, 15, 15, 17],
       [10, 17, 15, 16]], dtype=int32)

In [110]:
# same as random
np.random.seed(10)
np.random.uniform(size=(3,5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096]])

In [111]:
np.random.seed(10)
np.random.uniform(10.0, 50.0, size=(3,5))

array([[40.85282573, 10.83007797, 35.3459294 , 39.9521553 , 29.94028049],
       [18.99186582, 17.92251459, 40.42122849, 16.76443346, 13.53359257],
       [37.41439273, 48.13573385, 10.15793065, 30.48769054, 42.50483847]])

In [129]:
np.random.seed(10)
np.random.choice(np.array([1, 2, 3]), size=10)

array([2, 2, 1, 1, 2, 1, 2, 2, 1, 2])

In [130]:
np.random.seed(10)
np.random.choice(np.array(['a', 'b', 'c']), size=10)

array(['b', 'b', 'a', 'a', 'b', 'a', 'b', 'b', 'a', 'b'], dtype='<U1')