In [2]:
import numpy as np

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(15, 25)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
np.arange(start=20, stop=30, step=3)

array([20, 23, 26, 29])

In [9]:
np.arange(-15, 5, 4)

array([-15, -11,  -7,  -3,   1])

In [11]:
np.arange(20).reshape([2, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [13]:
np.arange(20).reshape([2, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [24]:
np.arange(100).reshape([5, 5, 4]).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
np.arange(20).reshape([4, 5]).reshape([2, 2, 5]).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
np.random.random((10,))

array([0.92200642, 0.30484854, 0.38237386, 0.29753497, 0.00718363,
       0.70937904, 0.8490254 , 0.51548772, 0.71183121, 0.04740424])

In [22]:
np.random.random((10,)).reshape((2, 5)).flatten()

array([0.54088093, 0.13145815, 0.41366737, 0.77872881, 0.58390137,
       0.18263144, 0.82608225, 0.10540183, 0.28357668, 0.06556327])

In [19]:
np.random.seed(10)
np.random.randint(50, 80, (4, 3, 3))

array([[[59, 79, 54],
        [65, 50, 67],
        [77, 78, 75]],

       [[79, 66, 79],
        [67, 76, 58],
        [59, 50, 60]],

       [[58, 72, 54],
        [69, 66, 54],
        [65, 61, 72]],

       [[74, 61, 76],
        [51, 58, 54],
        [64, 67, 69]]], dtype=int32)

In [20]:
np.random.seed(10)
np.random.randint(50, 80, (4, 3, 3)).flatten()

array([59, 79, 54, 65, 50, 67, 77, 78, 75, 79, 66, 79, 67, 76, 58, 59, 50,
       60, 58, 72, 54, 69, 66, 54, 65, 61, 72, 74, 61, 76, 51, 58, 54, 64,
       67, 69], dtype=int32)

In [21]:
np.arange(30).reshape((4, 10))

ValueError: cannot reshape array of size 30 into shape (4,10)

In [26]:
np.arange(125).reshape((5, 5, 5))

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])