In [1]:
import numpy as np

## 1. Calculating Total Revenue

In [3]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [4]:
quantities = np.array([10, 5, 8, 12, 3])
quantities

array([10,  5,  8, 12,  3])

In [5]:
revenue_per_product = prices * quantities
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [7]:
total_revenue = np.sum(revenue_per_product)
total_revenue

np.float64(664.62)

## 2. Analyzing Blog Post Stats

In [8]:
views = np.array([100, 500, 800, 1200, 300, 600])
views

array([ 100,  500,  800, 1200,  300,  600])

In [9]:
max_views = np.max(views)
max_views

np.int64(1200)

In [10]:
min_views = np.min(views)
min_views

np.int64(100)

In [12]:
average_views = np.round(np.mean(views), 2)
average_views

np.float64(583.33)

In [13]:
total_views = np.sum(views)
total_views

np.int64(3500)

## 3. Spltting Order into Batches

In [17]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])

In [18]:
batches = np.split(order_ids, 4)
batches

[array([1001, 1002]),
 array([1003, 1004]),
 array([1005, 1006]),
 array([1007, 1008])]

In [20]:
for batch in batches:
    print("First element in the batch: ", batch[0])
    print("Second element in the batch: ", batch[1])
    

First element in the batch:  1001
Second element in the batch:  1002
First element in the batch:  1003
Second element in the batch:  1004
First element in the batch:  1005
Second element in the batch:  1006
First element in the batch:  1007
Second element in the batch:  1008


In [22]:
for i, batch in enumerate(batches):
    print(f"Batch nuber {i}:")
    print("First element in the batch: ", batch[0])
    print("Second element in the batch: ", batch[1])
    

Batch nuber 0:
First element in the batch:  1001
Second element in the batch:  1002
Batch nuber 1:
First element in the batch:  1003
Second element in the batch:  1004
Batch nuber 2:
First element in the batch:  1005
Second element in the batch:  1006
Batch nuber 3:
First element in the batch:  1007
Second element in the batch:  1008


## 4. Categorizing Product Ratings

In [23]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 2.5, 4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 2.5, 4.7])

In [25]:
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.5, 5. , 4.1, 4.7])

In [26]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.2, 2.8, 3.9, 2.5])

## 5. Calculate Total and Average quantities sold

In [33]:
# Each column is specific product (we have 4 products)
# Each row is specific order
order_quantities = np.array([[5, 3, 2, 7], [10, 6, 3, 9]])
order_quantities

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [30]:
total_quantities_sold = order_quantities[0] + order_quantities[1]
total_quantities_sold

array([15,  9,  5, 16])

In [32]:
# Quantities of the sales per product
total_quantities_sold_2 = np.sum(order_quantities, axis=0)
total_quantities_sold_2

array([15,  9,  5, 16])

In [34]:
# Quantities of the sales per order
total_products_per_order = np.sum(order_quantities, axis=1)
total_products_per_order

array([17, 28])

In [37]:
# Avarage quantities per product across all orders
avarage_quantities_sold = np.mean(order_quantities, axis=0)
avarage_quantities_sold

array([7.5, 4.5, 2.5, 8. ])

In [36]:
avarage_quantities_per_order = np.mean(order_quantities, axis=1)
avarage_quantities_per_order

array([4.25, 7.  ])

## 6. Calculate Average product Rating and Maximum rating per Category

In [38]:
# Each row is one product
# Each product is rated in 4 categories
product_ratings = np.array([
    [4.5, 3.2, 2.5, 5.0],
    [4.3, 3.8, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5]
])
product_ratings

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [40]:
# Average rating in each category
average_rating_per_category = np.mean(product_ratings, axis=0)
average_rating_per_category

array([3.6       , 3.53333333, 2.73333333, 3.43333333])

In [41]:
# Average rating in each product
average_rating_per_product = np.mean(product_ratings, axis=1)
average_rating_per_product

array([3.8  , 3.475, 2.7  ])

In [42]:
# Maximum rating in each category
max_rating_per_category = np.max(product_ratings, axis=0)
max_rating_per_category

array([4.5, 3.8, 4.7, 5. ])

## 7. Generation of the sample stock data

In [53]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Mon 1 April', 'Tue 2 April']
price_types = ['Open', 'Close', 'High', 'Low']

In [54]:
# shape will be(3, 2, 4)
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [49]:
stock_prices.shape

(3, 2, 4)

In [56]:
for index_axis_0, company in enumerate(companies):
    print(f"Stock prices for the {company}:")
    for index_axis_1, day in enumerate(days):
        print(f"Day: {day}")
        for index_axis_2, price_type in enumerate(price_types):
            print(f"{price_type} Price: {stock_prices[index_axis_0, index_axis_1, index_axis_2]}")
        print('')
    print('')

Stock prices for the Google:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day: Tue 2 April
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346


Stock prices for the Microsoft:
Day: Mon 1 April
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day: Tue 2 April
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67


Stock prices for the Apple:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day: Tue 2 April
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692


