In [1]:
import numpy as np

In [3]:
first = np.array([[1, 2, 3],[4, 5, 6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
second = np.array([[7, 8, 9],[10, 11, 12]])
second

array([[ 7,  8,  9],
       [10, 11, 12]])

In [8]:
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

In [9]:
first + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [10]:
first - 2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [11]:
first * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
first / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [13]:
first

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
first[1, 1]

np.int64(5)

In [16]:
first[1][1]

np.int64(5)

In [17]:
first.shape

(2, 3)

In [19]:
np.concatenate((first, second))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
third = np.concatenate((first, second))
third

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
third.shape

(4, 3)

In [27]:
np.concatenate((second, first), axis=1)

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

In [28]:
np.concatenate((np.array([1, 2, 3, 4]), np.array([5, 6, 7, 8])))

array([1, 2, 3, 4, 5, 6, 7, 8])